name: Notify Slack
description: Notify Slack
inputs:
  channel_id: # channel id to post message when using bot token
    description: 'Slack channel ID where message will be posted. Needed if using bot token'
    required: false
  outcome:
    description: "Tells the action if it's a success outcome"
    required: false
    default: 'failure'
  token:
    description: "Slack app api token"
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Send success slack notification
      if: ${{ inputs.outcome == 'success' }}
      shell: bash
      run: |
        ls -al
        echo "-----------"
        curl -H "Content-Type: application/json" \
            -d success.json
             -H "Authorization: Bearer xoxb-${{ inputs.token }}" \
             -X POST https://slack.com/api/chat.postMessage \
    - name: Send failure slack notification
      if: ${{ inputs.outcome == 'failure' }}
      shell: bash
      run: |
        curl -H "Content-Type: application/json" \
             -H "Authorization: Bearer xoxb-${{ inputs.token }}" \
             -X POST https://slack.com/api/chat.postMessage \
            --data \
        "
        {
          \"channel\": ${{ inputs.channel_id }},
          \"blocks\": [
            {
              \"type\": \"section\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"*status:* failure \"
              }
            },
            {
              \"type\": \"section\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"*repository:* ${{ github.repository }} \"
              }
            },
            {
              \"type\": \"divider\"
            },
            {
              \"type\": \"section\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"Action success\"
              }
            },
            {
              \"type\": \"section\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"Check it by clicking the button\"
              },
              \"accessory\": {
                \"type\": \"button\",
                \"text\": {
                  \"type\": \"plain_text\",
                  \"text\": \"PR Url\",
                  \"emoji\": true
                },
                \"value\": \"click_me_123\",
                \"url\": ${{ github.event.pull_request.html_url }},
                \"action_id\": \"button-action\"
              }
            }
          ]
        }"
