name: Notify Slack
description: Notify Slack
inputs:
  channel_id: # channel id to post message when using bot token
    description: 'Slack channel ID where message will be posted. Needed if using bot token'
    required: false
  outcome:
    description: "Tells the action if it's a success outcome"
    required: false
    default: 'failure'
  token:
    description: "Slack app api token"
    required: true
runs:
  using: composite
  steps:
    - name: Send success slack notification
      if: ${{ inputs.outcome == 'success' }}
      shell: bash
      run: |
        echo "github repo_url:"
        echo ${{ github.repositoryUrl }}
        echo "github workflow: "
        echo ${{ github.workflow }}
        echo "github head_ref: "
        echo ${{ github.head_ref }}
        echo "github ref: "
        echo ${{ github.ref }}
        echo ${{ github.ref_name }}
        echo "github base_ref: "
        echo ${{ github.base_ref }}
        echo "github actor: "
        echo ${{ github.actor }}
        echo "github action: "
        echo ${{ github.action }}
        echo "runner name:"
        echo ${{ runner.name }}

        curl -X POST https://slack.com/api/chat.postMessage \
             -H "Authorization: Bearer xoxb-${{ inputs.token }}" \
             -H "Accept: application/json" \
             -H "Content-Type: application/json" \
             --data '{ "channel": "${{ inputs.channel_id }}", "blocks": [{ "type": "section", "text": { "type": "mrkdwn", "text": "*status:* success " } }, { "type": "section", "text": { "type": "mrkdwn", "text": "*repository:* ${{ github.repository }}" } }, { "type": "divider" }, { "type": "section", "text": { "type": "mrkdwn", "text": "Check it by clicking the button" }, "accessory": { "type": "button", "text": { "type": "plain_text", "text": "PR Url", "emoji": true }, "value": "click_me_123", "url": "https://github.com/dreamstechnology/demo-test-githubaction-repo", "action_id": "button-action" } } ] }'

