name: Notify Slack
description: Notify Slack
inputs:
  channel_id: # channel id to post message when using bot token
    description: 'Slack channel ID where message will be posted. Needed if using bot token'
    required: false
  outcome:
    description: "Tells the action if it's a success outcome"
    required: false
    default: 'failure'
  token:
    description: "Slack app api token"
    required: true
runs:
  using: composite
  steps:
    - name: Send success slack notification
      if: ${{ inputs.outcome == 'success' }}
      shell: bash
      run: |
        curl -X POST https://slack.com/api/chat.postMessage \
             -H "Authorization: Bearer xoxb-${{ inputs.token }}" \
             -H "Accept: application/json" \
             -H "Content-Type: application/json" \
             --data '{ "channel": "${{ inputs.channel_id }}", "blocks": [ { "type": "divider" }, { "type": "header", "text": { "type": "plain_text", "text": "*${{ github.workflow }}* success" } }, { "type": "section", "text": { "type": "mrkdwn", "text": ":white_check_mark: *<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|feature/compose-slack-msg>*" } }, { "type": "context", "elements": [ { "type": "mrkdwn", "text": "*SHA:* `${{ github.sha }}`" }, { "type": "mrkdwn", "text": "*Repo:* <https://github.com/${{github.repository}}|${{ github.repository }}>" } ] }, { "type": "divider" } ] }'
    - name: Send success slack notification
      if: ${{ inputs.outcome == 'failure' }}
      shell: bash
      run: |
        curl -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer xoxb-${{ inputs.token }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{ "channel": "${{ inputs.channel_id }}", "blocks": [ { "type": "divider" }, { "type": "header", "text": { "type": "plain_text", "text": "*${{ github.workflow }}* failed" } }, { "type": "section", "text": { "type": "mrkdwn", "text": ":x: *<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|feature/compose-slack-msg>*" } }, { "type": "context", "elements": [ { "type": "mrkdwn", "text": "*SHA:* `${{ github.sha }}`" }, { "type": "mrkdwn", "text": "*Repo:* <https://github.com/${{github.repository}}|${{ github.repository }}>" } ] }, { "type": "divider" } ] }'


